version: '3.8'

services:
  api:
    user: root
    working_dir: /usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: attendease-api
    restart: always
    ports:
      - '3012:3012'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - attendease-network
networks:
  attendease-network:
    external: true
