version: '3.8'
services:
  postgres:
    container_name: postgres
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - attendease-network
volumes:
  postgres-data:
networks:
  attendease-network:
    driver: bridge
